server:
  port: 10001
  servlet:
    context-path: /swagger
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///jpa?useSSL=false
    username: root
    password: 1234
  # jpa
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  # 热部署生效
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  freemarker:
    cache: false
  thymeleaf:
    cache: false
debug: true